# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
      init:
        data-locations: classpath:db/data/data-h2.sql
        schema-locations: classpath:db/schema/schema-h2.sql
